on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  pruebas:
    name: Ejecutar pruebas
    runs-on: ubuntu-latest
    steps:
      - name: Descargar c贸digo
        uses: actions/checkout@v4

      - name: Configurar Buildx
        uses: docker/setup-buildx-action@v3

      - name: Ejecutar tests
        uses: docker/build-push-action@v6
        with:
          context: .
          target: test
          push: false

  produccion:
    name: Construir y subir imagen
    runs-on: ubuntu-latest
    needs: pruebas
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - name: Descargar c贸digo
        uses: actions/checkout@v4

      - name: Iniciar sesi贸n en Docker Hub
        run: docker login -u ${{ secrets.NAME_DOCKER_HUP }} -p ${{ secrets.TOKEN_DOCKER_HUP }}

      - name: Configurar QEMU
        uses: docker/setup-qemu-action@v3

      - name: Configurar Buildx
        uses: docker/setup-buildx-action@v3

      - name: Construir y subir imagen de producci贸n
        uses: docker/build-push-action@v6
        with:
          context: .
          target: production
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ secrets.NAME_DOCKER_HUP }}/taskapp:latest
